---
- name: Validate proxy
  hosts: all
  gather_facts: yes
  tags: proxy
  vars:
    proxy_uc_envs:
    - HTTP_PROXY
    - HTTPS_PROXY
    proxy_lc_envs:
    - http_proxy
    - https_proxy
    proxies:
    - "{{ proxy_http }}"
    - "{{ proxy_https }}"
  vars_files:
  - "{{file_env}}"
  - "{{file_secrets}}"
  roles:
  - check_proxy

- name: ensure bastion packages.
  hosts: bastion
  tags: packages
  gather_facts: yes
  vars_files:
  - "{{file_env}}"
  roles:
  - check_packages_bastion

- name: ensure subscription
  gather_facts: no
  hosts: nodes
  tags: subscription
  vars_files:
  - "{{file_env}}"
  - "{{file_secrets}}"
  roles:
  - check_subscription


- name: ensure nodes packages.
  hosts: nodes
  tags: packages
  serial: 1
  gather_facts: no
  vars_files:
  - "{{file_env}}"
  roles:
  - check_packages_nodes

- name: ensure nodes networking.
  hosts: all
  tags: networking
  serial: 1
  gather_facts: no
  vars_files:
  - "{{file_env}}"
  roles:
  - check_networking


- name: Validate environment
  gather_facts: no
  hosts: all
  tags: validate
  vars_files:
  - "{{file_env}}"
  - "{{file_secrets}}"
  tasks:
    - import_role:
        name: check_disks
    - import_role:
        name: check_os
    - import_role:
        name: check_connectivity
    - import_role:
        name: check_sizing
      when: inventory_hostname in groups['nodes']
    - import_role:
        name: check_dns
    - import_role:
        name: check_selinux
    - import_role:
        name: check_ntp
      when: ntp_servers is defined
    - import_role:
        name: check_storage
      when: inventory_hostname in groups['nodes']
    - import_role:
        name: check_nm
    - import_role:
        name: check_glusterfs
      when: inventory_hostname in groups['glusterfs'] | default([])


- name: Initialize firewall check
  hosts: nodes
  tags: firewall
  gather_facts: no
  vars_files:
  - "{{file_env}}"
  roles:
  - check_firewall_initialize

- name: Execute firewall check
  hosts: localhost
  tags: firewall
  gather_facts: yes
  vars_files:
  - "{{file_env}}"
  roles:
  - check_firewall

- name: Validate docker
  hosts: nodes
  tags: docker
  gather_facts: yes
  vars_files:
  - "{{file_env}}"
  roles:
  - check_docker_setup
  - check_docker_validation

- name: Cleanup validation trash
  hosts: all
  tags: cleanup
  gather_facts: yes
  vars_files:
  - "{{file_env}}"
  roles:
  - check_cleanup
